import type { BlackMarketOfferDef } from '../types';

export const P2_BLACK_MARKET_OFFERS: BlackMarketOfferDef[] = [
  {
    id: 'offer-alien-egg',
    title: '卖家委托：会呼吸的蛋',
    sellerId: 'man-in-black',
    targetId: 'blackmarket-alien-egg',
    phase: 'p2',
    rarity: 'common',
    cost: { money: 650, reputation: 1 },
    limited: true,
    unique: false,
    lock: { rumors: ['rumor-black-market-missile'] },
    acceptText: '卖家把蛋放下，桌子自己往后退了一点。',
    declineText: '卖家没生气，只把蛋拿近了一点。',
  },
  {
    id: 'offer-meteor-core',
    title: '限时稀有货：倒着掉的陨石核',
    sellerId: 'man-in-black',
    targetId: 'blackmarket-meteor-core',
    phase: 'p2',
    rarity: 'rare',
    cost: { money: 1000, reputation: 2 },
    limited: true,
    unique: false,
    lock: { rumors: ['rumor-meteor-core'], completedTargets: ['blackmarket-alien-egg'], reputation: 2 },
    acceptText: '卖家说搬运费另算，老哥说地心引力也别算。',
    declineText: '陨石核往天花板蹭了一下，卖家的脸色也往下掉。',
  },
  {
    id: 'offer-sealed-vault',
    title: '独一无二：没有钥匙孔的黑箱',
    sellerId: 'man-in-black',
    targetId: 'blackmarket-sealed-vault',
    phase: 'p2',
    rarity: 'legendary',
    cost: { money: 1400, reputation: 3 },
    limited: true,
    unique: true,
    lock: { rumors: ['rumor-black-vault'], completedTargets: ['blackmarket-meteor-core'], reputation: 3 },
    acceptText: '卖家要求别看账本，老哥要求账本别太硬。',
    declineText: '卖家记下一笔：老哥今天没胆。',
  },
  {
    id: 'offer-ufo-hull',
    title: '黑市最终单：不明飞船外壳',
    sellerId: 'man-in-black',
    targetId: 'ufo-hull',
    phase: 'p2',
    rarity: 'unique',
    cost: { money: 9800, reputation: 10 },
    limited: true,
    unique: true,
    lock: {
      rumors: ['rumor-ufo-hull'],
      completedTargets: ['expedition-gundam-factory', 'expedition-collider'],
      reputation: 10,
      runCount: 3,
    },
    acceptText: '合同没有纸，只有一片会发光的壳。',
    declineText: '卖家第一次问：你确定不是它在拒绝你？',
  },
];

export const P2_BLACK_MARKET_OFFER_MAP = Object.fromEntries(
  P2_BLACK_MARKET_OFFERS.map((offer) => [offer.id, offer]),
);
