import type { ToolDef } from '../types';

export const P2_TOOLS: ToolDef[] = [
  {
    id: 'mecha-fist',
    kind: 'tool',
    name: '破烂机甲巨拳',
    tags: ['mecha', 'hammer'],
    power: 42,
    durability: 220,
    price: 0,
    materialBonus: { metal: 1.55, stone: 1.25, organic: 1.1 },
  },
  {
    id: 'mecha-shoulder-ram',
    kind: 'tool',
    name: '机甲肩部冲锤',
    tags: ['mecha', 'hydraulic'],
    power: 54,
    durability: 190,
    price: 0,
    materialBonus: { metal: 1.65, stone: 1.35 },
  },
  {
    id: 'gundam-pile',
    kind: 'tool',
    name: '高达级冲桩臂',
    tags: ['gundam', 'hydraulic'],
    power: 72,
    durability: 260,
    price: 0,
    materialBonus: { metal: 1.9, stone: 1.65, anomaly: 1.2, volatile: 1.05 },
  },
  {
    id: 'ultra-beam',
    kind: 'tool',
    name: '巨大化光线砸',
    tags: ['ultra', 'absurd'],
    power: 96,
    durability: 180,
    price: 0,
    materialBonus: { anomaly: 1.9, organic: 1.45, stone: 1.4 },
  },
  {
    id: 'ultra-stomp',
    kind: 'tool',
    name: '巨大化踩踏',
    tags: ['ultra', 'hammer'],
    power: 88,
    durability: 170,
    price: 0,
    materialBonus: { stone: 1.75, metal: 1.35, organic: 1.25 },
  },
  {
    id: 'ultra-flying-kick',
    kind: 'tool',
    name: '巨大化飞踢',
    tags: ['ultra', 'absurd'],
    power: 102,
    durability: 150,
    price: 0,
    materialBonus: { anomaly: 1.55, volatile: 1.2, metal: 1.25 },
  },
];
