import type { TargetDef } from '../types';

const parcelArt = '/game-art/icons/parcel-standard.png';
const parcelSmallArt = '/game-art/icons/parcel-small.png';
const parcelCrateArt = '/game-art/icons/parcel-crate.png';
const parcelReinforcedArt = '/game-art/icons/parcel-reinforced.png';
const tapeArt = '/game-art/icons/fx-tape.png';
const safeArt = '/game-art/icons/shop-safe.png';
const carArt = '/game-art/icons/giant-g-car.png';
const missileArt = '/game-art/icons/shop-missile.png';
const depotBg = '/game-art/backgrounds/stage-1-depot.png';
const marketBg = '/game-art/backgrounds/stage-2-market.png';
const factoryBg = '/game-art/backgrounds/stage-3-factory.png';

export const P1_TARGETS: TargetDef[] = [
  {
    id: 'parcel-basic',
    name: '普通快递',
    scale: 'desktop',
    presentation: 'workbench',
    phase: 'p1',
    intro: '热身用的小纸箱，砸开就有钱，砸快一点老哥就来劲。',
    icon: parcelArt,
    views: [
      {
        id: 'front',
        name: '工作台',
        background: depotBg,
        hotspots: [{ id: 'parcel-body-hotspot', partId: 'parcel-body', x: 0.38, y: 0.34, width: 0.24, height: 0.26 }],
      },
    ],
    parts: [
      {
        id: 'parcel-body',
        name: '纸箱本体',
        viewId: 'front',
        material: 'paper',
        hp: 6,
        stages: [
          { id: 'intact', threshold: 1, art: parcelArt, label: '胶带还挺牢' },
          { id: 'cracked', threshold: 0.5, art: tapeArt, label: '胶带开始松' },
          { id: 'open', threshold: 0, art: parcelArt, label: '开了' },
        ],
        machineSlots: [],
        riskTriggers: [],
      },
    ],
    risks: [],
    rewards: { cash: 28, items: ['tape', 'socks'], rumors: [], accidentArchives: [] },
    unlocks: [{ kind: 'target', id: 'parcel-combo' }],
  },
  {
    id: 'parcel-combo',
    name: '连击练手箱',
    scale: 'desktop',
    presentation: 'workbench',
    phase: 'p1',
    intro: '这个箱子不贵，但很适合让老哥按住不松手，把连击砸热。',
    icon: parcelSmallArt,
    views: [
      {
        id: 'front',
        name: '工作台',
        background: depotBg,
        hotspots: [{ id: 'combo-body-hotspot', partId: 'combo-body', x: 0.38, y: 0.34, width: 0.24, height: 0.26 }],
      },
    ],
    parts: [
      {
        id: 'combo-body',
        name: '软纸箱',
        viewId: 'front',
        material: 'paper',
        hp: 18,
        stages: [
          { id: 'intact', threshold: 1, art: parcelSmallArt, label: '纸箱还挺鼓' },
          { id: 'crumpled', threshold: 0.5, art: tapeArt, label: '胶带被砸热了' },
          { id: 'open', threshold: 0, art: parcelSmallArt, label: '连击砸开' },
        ],
        machineSlots: [],
        riskTriggers: [],
      },
    ],
    risks: [],
    rewards: { cash: 42, items: ['tape', 'foam', 'pen'], rumors: [], accidentArchives: [] },
    unlocks: [{ kind: 'target', id: 'parcel-cash' }],
  },
  {
    id: 'parcel-cash',
    name: '到付现金箱',
    scale: 'desktop',
    presentation: 'workbench',
    phase: 'p1',
    intro: '快递单写着到付，箱子里却哗啦响。砸开、卖钱、升级，流程就这么粗暴。',
    icon: parcelCrateArt,
    views: [
      {
        id: 'front',
        name: '工作台',
        background: depotBg,
        hotspots: [{ id: 'cash-body-hotspot', partId: 'cash-body', x: 0.36, y: 0.32, width: 0.28, height: 0.3 }],
      },
    ],
    parts: [
      {
        id: 'cash-body',
        name: '厚纸箱',
        viewId: 'front',
        material: 'paper',
        hp: 26,
        stages: [
          { id: 'intact', threshold: 1, art: parcelCrateArt, label: '贴着到付单' },
          { id: 'split', threshold: 0.5, art: tapeArt, label: '现金味出来了' },
          { id: 'open', threshold: 0, art: parcelCrateArt, label: '钱到手' },
        ],
        machineSlots: [],
        riskTriggers: [],
      },
    ],
    risks: [],
    rewards: { cash: 75, items: ['cashwad', 'screw'], rumors: [], accidentArchives: [] },
    unlocks: [{ kind: 'target', id: 'parcel-tool' }],
  },
  {
    id: 'parcel-tool',
    name: '硬壳工具箱',
    scale: 'desktop',
    presentation: 'workbench',
    phase: 'p1',
    intro: '这个开始有点硬。徒手能砸开，但买把锤子会舒服很多。',
    icon: parcelReinforcedArt,
    views: [
      {
        id: 'front',
        name: '工作台',
        background: depotBg,
        hotspots: [{ id: 'tool-body-hotspot', partId: 'tool-body', x: 0.35, y: 0.31, width: 0.3, height: 0.32 }],
      },
    ],
    parts: [
      {
        id: 'tool-body',
        name: '硬壳箱',
        viewId: 'front',
        material: 'wood',
        hp: 58,
        stages: [
          { id: 'intact', threshold: 1, art: parcelReinforcedArt, label: '硬壳完整' },
          { id: 'splinter', threshold: 0.5, art: parcelReinforcedArt, label: '木板裂了' },
          { id: 'open', threshold: 0, art: parcelReinforcedArt, label: '工具露出来' },
        ],
        machineSlots: [],
        riskTriggers: [],
      },
    ],
    risks: [],
    rewards: { cash: 110, scrap: 4, items: ['gear', 'screw'], rumors: [], accidentArchives: [] },
    unlocks: [{ kind: 'target', id: 'parcel-before-rage' }],
  },
  {
    id: 'parcel-before-rage',
    name: '安静得可疑的快递',
    scale: 'desktop',
    presentation: 'workbench',
    phase: 'p1',
    intro: '它很轻，也很安静。老哥觉得这反而不对劲。',
    icon: parcelArt,
    views: [
      {
        id: 'front',
        name: '工作台',
        background: depotBg,
        hotspots: [{ id: 'calm-body-hotspot', partId: 'calm-body', x: 0.38, y: 0.34, width: 0.24, height: 0.26 }],
      },
    ],
    parts: [
      {
        id: 'calm-body',
        name: '过渡快递',
        viewId: 'front',
        material: 'paper',
        hp: 36,
        stages: [
          { id: 'intact', threshold: 1, art: parcelArt, label: '它安静得过分' },
          { id: 'cracked', threshold: 0.5, art: tapeArt, label: '标签下面还有标签' },
          { id: 'open', threshold: 0, art: parcelArt, label: '只是开胃菜' },
        ],
        machineSlots: [],
        riskTriggers: [],
      },
    ],
    risks: [],
    rewards: { cash: 90, items: ['note', 'tape'], rumors: [], accidentArchives: [] },
    unlocks: [{ kind: 'target', id: 'parcel-tape-final' }],
  },
  {
    id: 'parcel-tape-final',
    name: '胶带缠了八百层的终极快递',
    scale: 'desktop',
    presentation: 'workbench',
    phase: 'p1',
    intro: '胶带、绳子、标签、泡沫、封条一层接一层，像在故意挑衅老哥。',
    icon: tapeArt,
    views: [
      {
        id: 'front',
        name: '快递收容站',
        background: depotBg,
        hotspots: [{ id: 'tape-body-hotspot', partId: 'tape-body', x: 0.32, y: 0.28, width: 0.36, height: 0.34 }],
      },
    ],
    parts: [
      {
        id: 'tape-body',
        name: '八百层胶带',
        viewId: 'front',
        material: 'paper',
        hp: 120,
        stages: [
          { id: 'tape', threshold: 1, art: tapeArt, label: '第一层胶带' },
          { id: 'rope', threshold: 0.75, art: tapeArt, label: '里面还有绳子' },
          { id: 'labels', threshold: 0.5, art: tapeArt, label: '标签底下还是胶带' },
          { id: 'foam', threshold: 0.25, art: tapeArt, label: '泡沫封条也来了' },
          { id: 'rage', threshold: 0, art: tapeArt, label: '老哥彻底暴怒' },
        ],
        machineSlots: [],
        riskTriggers: [{ riskId: 'anomaly-hum', level: 'suspicious', threshold: 0.25, hint: '箱子里面传来一声像倒放的低笑。' }],
      },
    ],
    risks: [{ riskId: 'anomaly-hum', partIds: ['tape-body'] }],
    rewards: {
      cash: 120,
      items: ['tape', 'foam'],
      rumors: ['rumor-old-market-safe'],
      accidentArchives: [],
    },
    unlocks: [
      { kind: 'panel', id: 'old-market' },
      { kind: 'target', id: 'safe-stubborn' },
    ],
  },
  {
    id: 'safe-stubborn',
    name: '撬不动的保险柜',
    scale: 'closeup',
    presentation: 'multi-part',
    phase: 'p1',
    intro: '锰钢门板，密码没人记得。里面可能是养老钱，也可能是一笔再也讨不回的债。',
    icon: safeArt,
    sellerId: 'retired-safe-master',
    views: [
      {
        id: 'front',
        name: '正面',
        background: marketBg,
        hotspots: [
          { id: 'safe-dial-hotspot', partId: 'safe-dial', x: 0.45, y: 0.35, width: 0.14, height: 0.14 },
          { id: 'safe-seam-hotspot', partId: 'safe-seam', x: 0.36, y: 0.52, width: 0.28, height: 0.08 },
        ],
      },
      {
        id: 'side',
        name: '侧面',
        background: marketBg,
        hotspots: [
          { id: 'safe-hinge-hotspot', partId: 'safe-hinge', x: 0.64, y: 0.28, width: 0.12, height: 0.34 },
          { id: 'safe-weld-hotspot', partId: 'safe-weld', x: 0.28, y: 0.62, width: 0.36, height: 0.08 },
        ],
      },
      {
        id: 'inside',
        name: '内层',
        background: marketBg,
        hotspots: [{ id: 'safe-inner-hotspot', partId: 'safe-inner-box', x: 0.4, y: 0.4, width: 0.22, height: 0.2 }],
      },
    ],
    parts: [
      {
        id: 'safe-dial',
        name: '锁盘',
        viewId: 'front',
        material: 'metal',
        hp: 160,
        stages: [
          { id: 'intact', threshold: 1, art: safeArt, label: '锁盘完整' },
          { id: 'loose', threshold: 0.5, art: safeArt, label: '锁盘松动' },
          { id: 'broken', threshold: 0, art: safeArt, label: '锁盘崩开' },
        ],
        machineSlots: [{ id: 'front-light-slot', accepts: ['crowbar', 'hydraulic'], x: 0.54, y: 0.48 }],
        riskTriggers: [{ riskId: 'trap-spring', level: 'suspicious', threshold: 0.35, hint: '锁盘后面传来绷紧的咔哒声。' }],
        unlocksParts: ['safe-inner-box'],
        unlocksViews: ['inside'],
      },
      {
        id: 'safe-seam',
        name: '门缝',
        viewId: 'front',
        material: 'metal',
        hp: 120,
        stages: [
          { id: 'intact', threshold: 1, art: safeArt, label: '门缝严丝合缝' },
          { id: 'warped', threshold: 0.5, art: safeArt, label: '门缝变形' },
          { id: 'open', threshold: 0, art: safeArt, label: '撬出缝了' },
        ],
        machineSlots: [{ id: 'front-pry-slot', accepts: ['crowbar'], x: 0.48, y: 0.58 }],
        riskTriggers: [],
      },
      {
        id: 'safe-hinge',
        name: '铰链',
        viewId: 'side',
        material: 'metal',
        hp: 180,
        stages: [
          { id: 'intact', threshold: 1, art: safeArt, label: '铰链完整' },
          { id: 'bent', threshold: 0.5, art: safeArt, label: '铰链歪了' },
          { id: 'off', threshold: 0, art: safeArt, label: '铰链飞了' },
        ],
        machineSlots: [{ id: 'side-hammer-slot', accepts: ['hydraulic', 'hammer'], x: 0.68, y: 0.42 }],
        riskTriggers: [{ riskId: 'trap-spring', level: 'dangerous', threshold: 0.2, hint: '铰链被砸到临界，里面的弹簧可能要弹出来。' }],
      },
      {
        id: 'safe-weld',
        name: '焊缝',
        viewId: 'side',
        material: 'metal',
        hp: 140,
        stages: [
          { id: 'intact', threshold: 1, art: safeArt, label: '焊缝很硬' },
          { id: 'split', threshold: 0.5, art: safeArt, label: '焊缝裂开' },
          { id: 'open', threshold: 0, art: safeArt, label: '侧面破口' },
        ],
        machineSlots: [{ id: 'side-weld-slot', accepts: ['hydraulic'], x: 0.43, y: 0.66 }],
        riskTriggers: [],
        skipAllowed: true,
      },
      {
        id: 'safe-inner-box',
        name: '内层小盒',
        viewId: 'inside',
        material: 'wood',
        hp: 70,
        stages: [
          { id: 'locked', threshold: 1, art: safeArt, label: '里面还有盒' },
          { id: 'splinter', threshold: 0.5, art: safeArt, label: '木盒裂开' },
          { id: 'done', threshold: 0, art: safeArt, label: '秘密到手' },
        ],
        machineSlots: [],
        riskTriggers: [{ riskId: 'anomaly-hum', level: 'unknown', threshold: 0.1, hint: '木盒里有一张完全漆黑的照片。' }],
      },
    ],
    risks: [
      { riskId: 'trap-spring', partIds: ['safe-dial', 'safe-hinge'] },
      { riskId: 'anomaly-hum', partIds: ['safe-inner-box'] },
    ],
    rewards: {
      cash: 450,
      scrap: 12,
      items: ['cashwad', 'ring', 'iou', 'carkey'],
      rumors: ['rumor-scrapyard-car'],
      accidentArchives: ['archive-spring-slap'],
      reputation: 1,
    },
    entryCost: { money: 120 },
    unlocks: [{ kind: 'target', id: 'car-scrapyard' }],
  },
  {
    id: 'car-scrapyard',
    name: '报废汽车',
    scale: 'scene',
    presentation: 'scene',
    phase: 'p1',
    intro: '挡风玻璃裂成蛛网，后备箱里还塞着前车主没处理完的东西。',
    icon: carArt,
    sellerId: 'used-car-laozhang',
    views: [
      {
        id: 'whole',
        name: '整车',
        background: factoryBg,
        hotspots: [
          { id: 'hood-hotspot', partId: 'car-hood', x: 0.22, y: 0.34, width: 0.2, height: 0.18 },
          { id: 'window-hotspot', partId: 'car-window', x: 0.43, y: 0.25, width: 0.18, height: 0.14 },
          { id: 'door-hotspot', partId: 'car-door', x: 0.44, y: 0.42, width: 0.18, height: 0.18 },
          { id: 'trunk-hotspot', partId: 'car-trunk', x: 0.66, y: 0.42, width: 0.2, height: 0.16 },
          { id: 'frame-hotspot', partId: 'car-frame', x: 0.3, y: 0.58, width: 0.45, height: 0.14 },
        ],
      },
      {
        id: 'front',
        name: '车头',
        background: factoryBg,
        hotspots: [
          { id: 'engine-hotspot', partId: 'car-engine', x: 0.32, y: 0.38, width: 0.28, height: 0.22 },
          { id: 'battery-hotspot', partId: 'car-battery', x: 0.62, y: 0.4, width: 0.14, height: 0.12 },
        ],
      },
      {
        id: 'rear',
        name: '后备箱',
        background: factoryBg,
        hotspots: [{ id: 'trunk-lock-hotspot', partId: 'car-trunk-lock', x: 0.45, y: 0.48, width: 0.18, height: 0.16 }],
      },
      {
        id: 'under',
        name: '底盘',
        background: factoryBg,
        hotspots: [{ id: 'under-device-hotspot', partId: 'car-under-device', x: 0.38, y: 0.5, width: 0.28, height: 0.16 }],
      },
      {
        id: 'finish',
        name: '终结',
        background: factoryBg,
        hotspots: [{ id: 'frame-final-hotspot', partId: 'car-frame', x: 0.28, y: 0.48, width: 0.48, height: 0.16 }],
      },
    ],
    parts: [
      {
        id: 'car-hood',
        name: '引擎盖',
        viewId: 'whole',
        material: 'metal',
        hp: 220,
        stages: [
          { id: 'intact', threshold: 1, art: carArt, label: '引擎盖还盖着' },
          { id: 'dented', threshold: 0.5, art: carArt, label: '引擎盖凹了' },
          { id: 'open', threshold: 0, art: carArt, label: '车头露出来了' },
        ],
        machineSlots: [{ id: 'hood-hydraulic-slot', accepts: ['hydraulic'], x: 0.34, y: 0.44 }],
        riskTriggers: [],
        unlocksViews: ['front'],
      },
      {
        id: 'car-window',
        name: '车窗',
        viewId: 'whole',
        material: 'stone',
        hp: 80,
        stages: [
          { id: 'intact', threshold: 1, art: carArt, label: '玻璃蛛网裂' },
          { id: 'cracked', threshold: 0.5, art: carArt, label: '玻璃快碎' },
          { id: 'gone', threshold: 0, art: carArt, label: '玻璃碎了一地' },
        ],
        machineSlots: [],
        riskTriggers: [],
      },
      {
        id: 'car-door',
        name: '车门',
        viewId: 'whole',
        material: 'metal',
        hp: 150,
        stages: [
          { id: 'closed', threshold: 1, art: carArt, label: '车门卡死' },
          { id: 'warped', threshold: 0.5, art: carArt, label: '车门被砸歪' },
          { id: 'open', threshold: 0, art: carArt, label: '车门飞开' },
        ],
        machineSlots: [{ id: 'door-arm-slot', accepts: ['hydraulic', 'crowbar'], x: 0.5, y: 0.5 }],
        riskTriggers: [],
      },
      {
        id: 'car-trunk',
        name: '后备箱盖',
        viewId: 'whole',
        material: 'metal',
        hp: 180,
        stages: [
          { id: 'shut', threshold: 1, art: carArt, label: '后备箱锁死' },
          { id: 'bent', threshold: 0.5, art: carArt, label: '后备箱变形' },
          { id: 'open', threshold: 0, art: carArt, label: '后备箱能看了' },
        ],
        machineSlots: [{ id: 'trunk-arm-slot', accepts: ['hydraulic', 'crowbar'], x: 0.72, y: 0.5 }],
        riskTriggers: [{ riskId: 'anomaly-hum', level: 'suspicious', threshold: 0.4, hint: '后备箱里滚了一下，但没有东西该会滚。' }],
        unlocksViews: ['rear'],
      },
      {
        id: 'car-frame',
        name: '车架',
        viewId: 'whole',
        material: 'metal',
        hp: 320,
        stages: [
          { id: 'holding', threshold: 1, art: carArt, label: '车架还撑着' },
          { id: 'buckled', threshold: 0.5, art: carArt, label: '车架开始折' },
          { id: 'flattened', threshold: 0, art: carArt, label: '整车压扁' },
        ],
        machineSlots: [{ id: 'frame-hydraulic-slot', accepts: ['hydraulic'], x: 0.52, y: 0.64 }],
        riskTriggers: [],
        unlocksViews: ['finish'],
      },
      {
        id: 'car-engine',
        name: '发动机',
        viewId: 'front',
        material: 'metal',
        hp: 260,
        stages: [
          { id: 'intact', threshold: 1, art: carArt, label: '发动机完整' },
          { id: 'loose', threshold: 0.5, art: carArt, label: '零件松了' },
          { id: 'scrapped', threshold: 0, art: carArt, label: '发动机报废' },
        ],
        machineSlots: [{ id: 'engine-hydraulic-slot', accepts: ['hydraulic'], x: 0.46, y: 0.48 }],
        riskTriggers: [],
      },
      {
        id: 'car-battery',
        name: '旧电池',
        viewId: 'front',
        material: 'volatile',
        hp: 90,
        stages: [
          { id: 'live', threshold: 1, art: carArt, label: '电池鼓包' },
          { id: 'hissing', threshold: 0.5, art: carArt, label: '电池冒烟' },
          { id: 'dead', threshold: 0, art: carArt, label: '电池拆下' },
        ],
        machineSlots: [{ id: 'battery-remote-slot', accepts: ['remote'], x: 0.68, y: 0.46 }],
        riskTriggers: [{ riskId: 'explosion-battery', level: 'dangerous', threshold: 0.5, hint: '电池开始发热，近身砸可能要出事。' }],
      },
      {
        id: 'car-trunk-lock',
        name: '后备箱锁',
        viewId: 'rear',
        material: 'metal',
        hp: 120,
        stages: [
          { id: 'locked', threshold: 1, art: carArt, label: '锁芯卡死' },
          { id: 'bent', threshold: 0.5, art: carArt, label: '锁芯歪了' },
          { id: 'open', threshold: 0, art: carArt, label: '后备箱打开' },
        ],
        machineSlots: [{ id: 'trunk-pry-slot', accepts: ['crowbar'], x: 0.52, y: 0.54 }],
        riskTriggers: [{ riskId: 'anomaly-hum', level: 'suspicious', threshold: 0.25, hint: '锁芯背后贴着一张没有影子的照片。' }],
      },
      {
        id: 'car-under-device',
        name: '底盘不明装置',
        viewId: 'under',
        material: 'volatile',
        hp: 140,
        stages: [
          { id: 'unknown', threshold: 1, art: missileArt, label: '看起来不该在车底' },
          { id: 'armed', threshold: 0.5, art: missileArt, label: '红灯开始闪' },
          { id: 'removed', threshold: 0, art: missileArt, label: '危险装置拆下' },
        ],
        machineSlots: [{ id: 'under-remote-slot', accepts: ['remote'], x: 0.52, y: 0.58 }],
        riskTriggers: [{ riskId: 'explosion-missile', level: 'critical', threshold: 0.5, hint: '这东西可能不是汽车零件。' }],
      },
    ],
    risks: [
      { riskId: 'explosion-battery', partIds: ['car-battery'] },
      { riskId: 'explosion-missile', partIds: ['car-under-device'] },
      { riskId: 'anomaly-hum', partIds: ['car-trunk', 'car-trunk-lock'] },
    ],
    rewards: {
      cash: 900,
      scrap: 80,
      items: ['r_scrapiron', 'r_wireharness', 'battery', 'carkey', 'p_gear'],
      rumors: ['rumor-black-market-missile'],
      accidentArchives: ['archive-car-battery-flash'],
      reputation: 2,
    },
    entryCost: { money: 450 },
    unlocks: [{ kind: 'target', id: 'missile-dont-touch' }],
  },
  {
    id: 'missile-dont-touch',
    name: '不该捡的导弹',
    scale: 'closeup',
    presentation: 'multi-part',
    phase: 'p1',
    intro: '理智的人会报警，但老哥只想知道里面那块芯片值多少钱。',
    icon: missileArt,
    sellerId: 'man-in-black',
    views: [
      {
        id: 'body',
        name: '弹体',
        background: factoryBg,
        hotspots: [
          { id: 'missile-body-hotspot', partId: 'missile-body', x: 0.22, y: 0.38, width: 0.42, height: 0.16 },
          { id: 'missile-fuse-hotspot', partId: 'missile-fuse', x: 0.64, y: 0.34, width: 0.16, height: 0.22 },
        ],
      },
    ],
    parts: [
      {
        id: 'missile-body',
        name: '弹体外壳',
        viewId: 'body',
        material: 'volatile',
        hp: 220,
        stages: [
          { id: 'sealed', threshold: 1, art: missileArt, label: '外壳完整' },
          { id: 'warning', threshold: 0.5, art: missileArt, label: '警告字样露出' },
          { id: 'open', threshold: 0, art: missileArt, label: '外壳打开' },
        ],
        machineSlots: [{ id: 'missile-remote-slot', accepts: ['remote'], x: 0.48, y: 0.52 }],
        riskTriggers: [{ riskId: 'explosion-missile', level: 'critical', threshold: 0.75, hint: '弹体还在装弹状态，老哥的直觉说该后退。' }],
      },
      {
        id: 'missile-fuse',
        name: '保险栓',
        viewId: 'body',
        material: 'volatile',
        hp: 80,
        stages: [
          { id: 'armed', threshold: 1, art: missileArt, label: '保险栓很不保险' },
          { id: 'loose', threshold: 0.5, art: missileArt, label: '保险栓松了' },
          { id: 'safe', threshold: 0, art: missileArt, label: '暂时安全' },
        ],
        machineSlots: [{ id: 'fuse-remote-slot', accepts: ['remote'], x: 0.7, y: 0.48 }],
        riskTriggers: [{ riskId: 'explosion-missile', level: 'dangerous', threshold: 0.35, hint: '保险栓一动，空气都安静了。' }],
      },
    ],
    risks: [{ riskId: 'explosion-missile', partIds: ['missile-body', 'missile-fuse'] }],
    rewards: {
      cash: 1200,
      scrap: 40,
      items: ['milchip', 'titanium', 'goldbar'],
      rumors: ['rumor-p2-monolith-shadow'],
      accidentArchives: ['archive-missile-boom'],
      reputation: 3,
    },
    entryCost: { money: 800 },
  },
];

// 货架商店专属：一个"看起来很牛逼但徒手/大锤根本砸不动"的怪东西。
// requiredTags=['remote'] —— 没有远程试探架就是 0 伤害，逼出博弈：当废铁卖 / 瞎砸 / 换货 / 回去拆快递。
// 一旦凑到远程装置，它就能砸开，掉落机器升级用的稀有材料。
P1_TARGETS.push({
  id: 'oddity-blackball',
  name: '不讲道理的黑铁球',
  scale: 'desktop',
  presentation: 'workbench',
  phase: 'p1',
  intro: '卖家说这是「陨星压缩核」，沉得像有人在里面拽。徒手和大锤砸上去只有闷响，连个白印都没有。',
  icon: safeArt,
  views: [
    {
      id: 'front',
      name: '工作台',
      background: marketBg,
      hotspots: [{ id: 'blackball-hotspot', partId: 'blackball-core', x: 0.38, y: 0.34, width: 0.24, height: 0.26 }],
    },
  ],
  parts: [
    {
      id: 'blackball-core',
      name: '致密核',
      viewId: 'front',
      material: 'volatile',
      hp: 110,
      requiredTags: ['remote'],
      stages: [
        { id: 'sealed', threshold: 1, art: safeArt, label: '一点都没动' },
        { id: 'humming', threshold: 0.5, art: safeArt, label: '开始低频嗡鸣' },
        { id: 'cracked', threshold: 0, art: safeArt, label: '核裂开了' },
      ],
      machineSlots: [{ id: 'blackball-remote-slot', accepts: ['remote'], x: 0.5, y: 0.46 }],
      riskTriggers: [],
    },
  ],
  risks: [],
  rewards: { cash: 260, scrap: 8, items: ['m_hardcore', 'm_pressgem', 'goldbar'], rumors: [], accidentArchives: [] },
});

export const P1_TARGET_MAP = Object.fromEntries(P1_TARGETS.map((target) => [target.id, target]));
