import type { TargetDef } from '../types';

const marketBg = '/game-art/backgrounds/stage-2-market.png';
const factoryBg = '/game-art/backgrounds/stage-3-factory.png';
const reactorBg = '/game-art/backgrounds/stage-4-reactor.png';
const launchpadBg = '/game-art/backgrounds/mission-m-launchpad.png';
const buildingBg = '/game-art/backgrounds/mission-m-building.png';
const bridgeBg = '/game-art/backgrounds/mission-m-bridge.png';
const nuclearBg = '/game-art/backgrounds/mission-m-nuclear.png';
const stationBg = '/game-art/backgrounds/mission-m-station.png';
const colliderBg = '/game-art/backgrounds/mission-m-collider.png';
const gundamFactoryBg = '/game-art/backgrounds/mission-m-gundamfac.png';

const alienEggArt = '/game-art/icons/shop-alienegg.png';
const meteorArt = '/game-art/icons/shop-meteor.png';
const blackMarketArt = '/game-art/icons/shop-blackmarket.png';
const pipelineArt = '/game-art/icons/blueprint-bp-pipeline-heavy.png';
const launchpadArt = '/game-art/icons/mission-m-launchpad.png';
const buildingArt = '/game-art/icons/mission-m-building.png';
const bridgeArt = '/game-art/icons/mission-m-bridge.png';
const nuclearArt = '/game-art/icons/mission-m-nuclear.png';
const stationArt = '/game-art/icons/mission-m-station.png';
const colliderArt = '/game-art/icons/mission-m-collider.png';
const mechaArt = '/game-art/icons/absurd-a-transformer.png';
const gundamArt = '/game-art/icons/absurd-a-gundam.png';
const ufoArt = '/game-art/icons/absurd-a-ufo.png';
const monolithArt = '/game-art/icons/absurd-a-monolith.png';

export const P2_TARGETS: TargetDef[] = [
  {
    id: 'blackmarket-alien-egg',
    name: '会呼吸的黑市蛋',
    scale: 'closeup',
    presentation: 'multi-part',
    phase: 'p2',
    intro: '卖家说别听它呼吸，老哥说不听怎么知道砸哪。',
    icon: alienEggArt,
    sellerId: 'man-in-black',
    views: [
      {
        id: 'shell',
        name: '蛋壳',
        background: marketBg,
        hotspots: [
          { id: 'egg-shell-hotspot', partId: 'egg-shell', x: 0.34, y: 0.28, width: 0.32, height: 0.32 },
          { id: 'egg-vein-hotspot', partId: 'egg-vein', x: 0.46, y: 0.48, width: 0.22, height: 0.22 },
        ],
      },
      {
        id: 'inside',
        name: '内膜',
        background: marketBg,
        hotspots: [{ id: 'egg-core-hotspot', partId: 'egg-core', x: 0.38, y: 0.34, width: 0.3, height: 0.28 }],
      },
    ],
    parts: [
      {
        id: 'egg-shell',
        name: '外层蛋壳',
        viewId: 'shell',
        material: 'organic',
        hp: 180,
        stages: [
          { id: 'whole', threshold: 1, art: alienEggArt, label: '壳在呼吸' },
          { id: 'cracked', threshold: 0.45, art: alienEggArt, label: '裂缝渗光' },
          { id: 'open', threshold: 0, art: alienEggArt, label: '外壳破开' },
        ],
        machineSlots: [{ id: 'egg-remote-slot', accepts: ['remote'], x: 0.5, y: 0.46 }],
        riskTriggers: [{ riskId: 'bio-egg-hatch', level: 'suspicious', threshold: 0.55, hint: '裂缝里有东西跟着锤声动。' }],
        unlocksViews: ['inside'],
        unlocksParts: ['egg-core'],
      },
      {
        id: 'egg-vein',
        name: '发光血管',
        viewId: 'shell',
        material: 'organic',
        hp: 90,
        stages: [
          { id: 'pulse', threshold: 1, art: alienEggArt, label: '一跳一跳' },
          { id: 'dim', threshold: 0.4, art: alienEggArt, label: '光在变暗' },
          { id: 'cut', threshold: 0, art: alienEggArt, label: '血管断开' },
        ],
        machineSlots: [{ id: 'egg-vein-remote', accepts: ['remote'], x: 0.56, y: 0.55 }],
        riskTriggers: [{ riskId: 'bio-egg-hatch', level: 'dangerous', threshold: 0.35, hint: '血管断开前，里面的东西醒了一下。' }],
      },
      {
        id: 'egg-core',
        name: '内层硬核',
        viewId: 'inside',
        material: 'anomaly',
        hp: 140,
        stages: [
          { id: 'sealed', threshold: 1, art: alienEggArt, label: '内膜包住核心' },
          { id: 'shaking', threshold: 0.45, art: alienEggArt, label: '核心乱跳' },
          { id: 'hatched', threshold: 0, art: alienEggArt, label: '砸出活物' },
        ],
        machineSlots: [{ id: 'egg-core-remote', accepts: ['remote'], x: 0.5, y: 0.5 }],
        riskTriggers: [{ riskId: 'bio-egg-hatch', level: 'critical', threshold: 0.45, hint: '内核不是硬，是在装死。' }],
      },
    ],
    risks: [{ riskId: 'bio-egg-hatch', partIds: ['egg-shell', 'egg-vein', 'egg-core'] }],
    rewards: {
      cash: 1600,
      scrap: 30,
      items: ['hatchling', 'alienalloy', 'crystal'],
      rumors: ['rumor-factory-line', 'rumor-meteor-core'],
      accidentArchives: ['archive-egg-bite'],
      reputation: 3,
    },
    entryCost: { money: 650, reputation: 1 },
    unlocks: [
      { kind: 'panel', id: 'black-market' },
      { kind: 'target', id: 'blackmarket-meteor-core' },
    ],
  },
  {
    id: 'blackmarket-meteor-core',
    name: '倒着掉的陨石核',
    scale: 'closeup',
    presentation: 'multi-part',
    phase: 'p2',
    intro: '它砸坏了仓库地板，又像在往天花板掉。',
    icon: meteorArt,
    sellerId: 'man-in-black',
    views: [
      {
        id: 'outer',
        name: '外壳',
        background: marketBg,
        hotspots: [
          { id: 'meteor-crust-hotspot', partId: 'meteor-crust', x: 0.28, y: 0.34, width: 0.42, height: 0.28 },
          { id: 'meteor-ring-hotspot', partId: 'meteor-ring', x: 0.46, y: 0.48, width: 0.22, height: 0.18 },
        ],
      },
      {
        id: 'core',
        name: '核心',
        background: marketBg,
        hotspots: [{ id: 'meteor-core-hotspot', partId: 'meteor-core', x: 0.38, y: 0.34, width: 0.3, height: 0.28 }],
      },
    ],
    parts: [
      {
        id: 'meteor-crust',
        name: '烧结外壳',
        viewId: 'outer',
        material: 'stone',
        hp: 260,
        stages: [
          { id: 'sealed', threshold: 1, art: meteorArt, label: '外壳烫手' },
          { id: 'cracked', threshold: 0.5, art: meteorArt, label: '外壳开裂' },
          { id: 'broken', threshold: 0, art: meteorArt, label: '陨铁剥落' },
        ],
        machineSlots: [{ id: 'meteor-crusher-slot', accepts: ['hydraulic', 'pipeline'], x: 0.48, y: 0.52 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'suspicious', threshold: 0.55, hint: '锤子落下前先轻了一下。' }],
        unlocksViews: ['core'],
        unlocksParts: ['meteor-core'],
      },
      {
        id: 'meteor-ring',
        name: '反重力环',
        viewId: 'outer',
        material: 'anomaly',
        hp: 150,
        stages: [
          { id: 'hum', threshold: 1, art: meteorArt, label: '环在低鸣' },
          { id: 'unstable', threshold: 0.45, art: meteorArt, label: '方向错乱' },
          { id: 'loose', threshold: 0, art: meteorArt, label: '反重力环脱落' },
        ],
        machineSlots: [{ id: 'meteor-ring-remote', accepts: ['remote'], x: 0.54, y: 0.55 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'dangerous', threshold: 0.45, hint: '碎屑没有往下掉。' }],
      },
      {
        id: 'meteor-core',
        name: '异常核心',
        viewId: 'core',
        material: 'anomaly',
        hp: 180,
        stages: [
          { id: 'covered', threshold: 1, art: meteorArt, label: '核心被包住' },
          { id: 'bright', threshold: 0.4, art: meteorArt, label: '核心变亮' },
          { id: 'split', threshold: 0, art: meteorArt, label: '核心裂开' },
        ],
        machineSlots: [{ id: 'meteor-core-remote', accepts: ['remote', 'pipeline'], x: 0.48, y: 0.5 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'critical', threshold: 0.35, hint: '核心把老哥的影子往上拽。' }],
      },
    ],
    risks: [{ riskId: 'anomaly-meteor-core', partIds: ['meteor-crust', 'meteor-ring', 'meteor-core'] }],
    rewards: {
      cash: 2200,
      scrap: 90,
      items: ['meteoriron', 'alienalloy', 'e_rare'],
      rumors: ['rumor-expedition-map', 'rumor-black-vault'],
      accidentArchives: ['archive-meteor-gravity'],
      reputation: 4,
    },
    entryCost: { money: 1000, reputation: 2 },
    unlocks: [
      { kind: 'panel', id: 'factory' },
      { kind: 'target', id: 'blackmarket-sealed-vault' },
      { kind: 'target', id: 'factory-pipeline-core' },
    ],
  },
  {
    id: 'blackmarket-sealed-vault',
    name: '没有钥匙孔的黑箱',
    scale: 'closeup',
    presentation: 'multi-part',
    phase: 'p2',
    intro: '卖家说砸开后如果看见账本，先别念出声。',
    icon: blackMarketArt,
    sellerId: 'man-in-black',
    views: [
      {
        id: 'front',
        name: '正面',
        background: marketBg,
        hotspots: [
          { id: 'vault-seal-hotspot', partId: 'vault-seal', x: 0.3, y: 0.32, width: 0.38, height: 0.2 },
          { id: 'vault-valve-hotspot', partId: 'vault-valve', x: 0.55, y: 0.46, width: 0.18, height: 0.2 },
        ],
      },
    ],
    parts: [
      {
        id: 'vault-seal',
        name: '无缝箱门',
        viewId: 'front',
        material: 'metal',
        hp: 280,
        stages: [
          { id: 'sealed', threshold: 1, art: blackMarketArt, label: '完全无缝' },
          { id: 'warped', threshold: 0.45, art: blackMarketArt, label: '箱门变形' },
          { id: 'open', threshold: 0, art: blackMarketArt, label: '箱门开裂' },
        ],
        machineSlots: [{ id: 'vault-pipeline-slot', accepts: ['pipeline', 'hydraulic'], x: 0.48, y: 0.48 }],
        riskTriggers: [{ riskId: 'corrosion-black-vault', level: 'dangerous', threshold: 0.5, hint: '箱门缝里冒出像铁锈一样的雾。' }],
      },
      {
        id: 'vault-valve',
        name: '隐藏泄压阀',
        viewId: 'front',
        material: 'metal',
        hp: 110,
        stages: [
          { id: 'hidden', threshold: 1, art: blackMarketArt, label: '阀口藏着' },
          { id: 'leaking', threshold: 0.4, art: blackMarketArt, label: '阀口漏雾' },
          { id: 'released', threshold: 0, art: blackMarketArt, label: '压力释放' },
        ],
        machineSlots: [{ id: 'vault-remote-slot', accepts: ['remote'], x: 0.62, y: 0.54 }],
        riskTriggers: [{ riskId: 'corrosion-black-vault', level: 'critical', threshold: 0.35, hint: '阀口在倒吸空气，像在等人靠近。' }],
      },
    ],
    risks: [{ riskId: 'corrosion-black-vault', partIds: ['vault-seal', 'vault-valve'] }],
    rewards: {
      cash: 3000,
      scrap: 120,
      items: ['cashwad', 'goldbar', 'p_circuit'],
      rumors: ['rumor-factory-line', 'rumor-expedition-map'],
      accidentArchives: ['archive-vault-fog'],
      reputation: 4,
    },
    entryCost: { money: 1400, reputation: 3 },
    unlocks: [
      { kind: 'panel', id: 'factory' },
      { kind: 'target', id: 'factory-pipeline-core' },
      { kind: 'target', id: 'expedition-launchpad' },
    ],
  },
  {
    id: 'factory-pipeline-core',
    name: '旧厂房三条废管线',
    scale: 'scene',
    presentation: 'scene',
    phase: 'p2',
    intro: '这里不是把货摆上桌，是把老哥的怒气装进管线。',
    icon: pipelineArt,
    views: [
      {
        id: 'line',
        name: '管线',
        background: factoryBg,
        hotspots: [
          { id: 'line-intake-hotspot', partId: 'line-intake', x: 0.18, y: 0.46, width: 0.24, height: 0.18 },
          { id: 'line-crusher-hotspot', partId: 'line-crusher', x: 0.42, y: 0.36, width: 0.24, height: 0.26 },
          { id: 'line-control-hotspot', partId: 'line-control', x: 0.68, y: 0.32, width: 0.18, height: 0.24 },
        ],
      },
    ],
    parts: [
      {
        id: 'line-intake',
        name: '进料口',
        viewId: 'line',
        material: 'metal',
        hp: 240,
        stages: [
          { id: 'jammed', threshold: 1, art: pipelineArt, label: '进料口卡死' },
          { id: 'loose', threshold: 0.45, art: pipelineArt, label: '轴承松动' },
          { id: 'ready', threshold: 0, art: pipelineArt, label: '进料口修好' },
        ],
        machineSlots: [{ id: 'line-intake-slot', accepts: ['hydraulic', 'crowbar'], x: 0.28, y: 0.52 }],
        riskTriggers: [{ riskId: 'corrosion-black-vault', level: 'suspicious', threshold: 0.45, hint: '旧油泥里混着黑箱同款腐蚀味。' }],
      },
      {
        id: 'line-crusher',
        name: '破碎机心脏',
        viewId: 'line',
        material: 'metal',
        hp: 320,
        stages: [
          { id: 'silent', threshold: 1, art: pipelineArt, label: '破碎机不动' },
          { id: 'sparking', threshold: 0.45, art: pipelineArt, label: '齿轮开始咬合' },
          { id: 'awake', threshold: 0, art: pipelineArt, label: '破碎线启动' },
        ],
        machineSlots: [{ id: 'line-crusher-slot', accepts: ['hydraulic', 'pipeline'], x: 0.5, y: 0.48 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'dangerous', threshold: 0.35, hint: '整条线动了一下，厂房梁也动了一下。' }],
      },
      {
        id: 'line-control',
        name: '控制柜',
        viewId: 'line',
        material: 'volatile',
        hp: 140,
        stages: [
          { id: 'dead', threshold: 1, art: pipelineArt, label: '控制柜没电' },
          { id: 'lit', threshold: 0.5, art: pipelineArt, label: '指示灯乱闪' },
          { id: 'online', threshold: 0, art: pipelineArt, label: '作业位上线' },
        ],
        machineSlots: [{ id: 'line-control-remote', accepts: ['remote'], x: 0.74, y: 0.42 }],
        riskTriggers: [{ riskId: 'pollution-reactor-leak', level: 'suspicious', threshold: 0.4, hint: '柜子里有一张核电站旧工单。' }],
      },
    ],
    risks: [
      { riskId: 'corrosion-black-vault', partIds: ['line-intake'] },
      { riskId: 'world-structure-collapse', partIds: ['line-crusher'] },
      { riskId: 'pollution-reactor-leak', partIds: ['line-control'] },
    ],
    rewards: {
      cash: 1800,
      scrap: 220,
      items: ['p_belt', 'p_servo', 'r_alloyblock'],
      rumors: ['rumor-expedition-map', 'rumor-reactor-route'],
      accidentArchives: [],
      reputation: 3,
    },
    entryCost: { money: 1200, reputation: 2 },
    unlocks: [
      { kind: 'panel', id: 'factory' },
      { kind: 'panel', id: 'expedition' },
      { kind: 'source', id: 'heavy-crusher' },
      { kind: 'source', id: 'crawler-press' },
      { kind: 'source', id: 'rail-smash-array' },
      { kind: 'target', id: 'expedition-launchpad' },
      { kind: 'target', id: 'expedition-building' },
    ],
  },
  {
    id: 'expedition-launchpad',
    name: '废弃火箭发射台',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '买不回来的东西，只能开车过去砸。',
    icon: launchpadArt,
    views: [
      {
        id: 'pad',
        name: '发射区',
        background: launchpadBg,
        hotspots: [
          { id: 'gantry-hotspot', partId: 'gantry', x: 0.22, y: 0.22, width: 0.22, height: 0.46 },
          { id: 'fuel-line-hotspot', partId: 'fuel-line', x: 0.48, y: 0.52, width: 0.28, height: 0.14 },
          { id: 'countdown-hotspot', partId: 'countdown-console', x: 0.72, y: 0.42, width: 0.16, height: 0.2 },
        ],
      },
    ],
    parts: [
      {
        id: 'gantry',
        name: '发射架',
        viewId: 'pad',
        material: 'metal',
        hp: 380,
        stages: [
          { id: 'standing', threshold: 1, art: launchpadArt, label: '发射架还站着' },
          { id: 'leaning', threshold: 0.45, art: launchpadArt, label: '钢架开始歪' },
          { id: 'down', threshold: 0, art: launchpadArt, label: '发射架倒下' },
        ],
        machineSlots: [{ id: 'gantry-pipeline', accepts: ['pipeline', 'hydraulic'], x: 0.32, y: 0.48 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'dangerous', threshold: 0.45, hint: '发射架一歪，半个场地都在响。' }],
      },
      {
        id: 'fuel-line',
        name: '残留燃料管',
        viewId: 'pad',
        material: 'volatile',
        hp: 170,
        stages: [
          { id: 'pressured', threshold: 1, art: launchpadArt, label: '管线有残压' },
          { id: 'leaking', threshold: 0.45, art: launchpadArt, label: '燃料味出来了' },
          { id: 'cut', threshold: 0, art: launchpadArt, label: '燃料管断开' },
        ],
        machineSlots: [{ id: 'fuel-remote', accepts: ['remote'], x: 0.6, y: 0.56 }],
        riskTriggers: [{ riskId: 'pollution-reactor-leak', level: 'dangerous', threshold: 0.35, hint: '残留燃料不该是这个颜色。' }],
      },
      {
        id: 'countdown-console',
        name: '倒计时控制台',
        viewId: 'pad',
        material: 'volatile',
        hp: 130,
        stages: [
          { id: 'off', threshold: 1, art: launchpadArt, label: '屏幕关着' },
          { id: 'counting', threshold: 0.5, art: launchpadArt, label: '倒计时自己亮了' },
          { id: 'stopped', threshold: 0, art: launchpadArt, label: '倒计时停下' },
        ],
        machineSlots: [{ id: 'countdown-remote', accepts: ['remote'], x: 0.78, y: 0.48 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'suspicious', threshold: 0.5, hint: '屏幕显示的数字不是时间，是周目数。' }],
      },
    ],
    risks: [
      { riskId: 'world-structure-collapse', partIds: ['gantry', 'countdown-console'] },
      { riskId: 'pollution-reactor-leak', partIds: ['fuel-line'] },
    ],
    rewards: {
      cash: 4200,
      scrap: 260,
      items: ['u_countdown', 'e_titanium', 'r_alloyblock'],
      rumors: ['rumor-reactor-route', 'rumor-space-route'],
      accidentArchives: ['archive-bridge-collapse'],
      reputation: 5,
    },
    entryCost: { money: 1800, reputation: 3 },
    unlocks: [
      { kind: 'target', id: 'expedition-bridge' },
      { kind: 'target', id: 'expedition-nuclear' },
    ],
  },
  {
    id: 'expedition-building',
    name: '烂尾楼整栋',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '老哥第一次不是砸一个东西，而是走进一个东西里面砸。',
    icon: buildingArt,
    views: [
      {
        id: 'ground',
        name: '底层',
        background: buildingBg,
        hotspots: [
          { id: 'pillar-hotspot', partId: 'pillar-row', x: 0.24, y: 0.32, width: 0.18, height: 0.38 },
          { id: 'sales-office-hotspot', partId: 'sales-office', x: 0.52, y: 0.46, width: 0.24, height: 0.2 },
          { id: 'roof-crane-hotspot', partId: 'roof-crane', x: 0.62, y: 0.18, width: 0.22, height: 0.2 },
        ],
      },
    ],
    parts: [
      {
        id: 'pillar-row',
        name: '承重柱排',
        viewId: 'ground',
        material: 'stone',
        hp: 420,
        stages: [
          { id: 'solid', threshold: 1, art: buildingArt, label: '承重柱完整' },
          { id: 'cracked', threshold: 0.45, art: buildingArt, label: '裂纹贯通' },
          { id: 'down', threshold: 0, art: buildingArt, label: '柱排倒塌' },
        ],
        machineSlots: [{ id: 'pillar-pipeline', accepts: ['pipeline', 'hydraulic'], x: 0.32, y: 0.5 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'critical', threshold: 0.4, hint: '再砸这里，楼会用自己的方式结算。' }],
      },
      {
        id: 'sales-office',
        name: '售楼处账柜',
        viewId: 'ground',
        material: 'wood',
        hp: 160,
        stages: [
          { id: 'locked', threshold: 1, art: buildingArt, label: '账柜上锁' },
          { id: 'open', threshold: 0.4, art: buildingArt, label: '票据飞出来' },
          { id: 'empty', threshold: 0, art: buildingArt, label: '账柜砸空' },
        ],
        machineSlots: [{ id: 'sales-crowbar', accepts: ['crowbar'], x: 0.62, y: 0.52 }],
        riskTriggers: [{ riskId: 'legal-city-response', level: 'dangerous', threshold: 0.5, hint: '账本上写着很多不该见光的名字。' }],
      },
      {
        id: 'roof-crane',
        name: '楼顶塔吊',
        viewId: 'ground',
        material: 'metal',
        hp: 300,
        stages: [
          { id: 'swing', threshold: 1, art: buildingArt, label: '塔吊悬着' },
          { id: 'loose', threshold: 0.4, art: buildingArt, label: '吊臂松了' },
          { id: 'fallen', threshold: 0, art: buildingArt, label: '塔吊落地' },
        ],
        machineSlots: [{ id: 'crane-pipeline', accepts: ['pipeline', 'remote'], x: 0.72, y: 0.22 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'dangerous', threshold: 0.45, hint: '塔吊的影子扫过半条街。' }],
      },
    ],
    risks: [
      { riskId: 'world-structure-collapse', partIds: ['pillar-row', 'roof-crane'] },
      { riskId: 'legal-city-response', partIds: ['sales-office'] },
    ],
    rewards: {
      cash: 4500,
      scrap: 300,
      items: ['u_deedstack', 'e_iron', 'r_scrapiron'],
      rumors: ['rumor-mecha-frame', 'rumor-reactor-route'],
      accidentArchives: ['archive-city-response'],
      reputation: 5,
    },
    entryCost: { money: 2000, reputation: 3 },
    unlocks: [
      { kind: 'target', id: 'expedition-bridge' },
      { kind: 'source', id: 'mecha-fist' },
      { kind: 'source', id: 'mecha-shoulder-ram' },
    ],
  },
  {
    id: 'expedition-bridge',
    name: '跨海大桥中段',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '这次目标大到老哥要走上去找地方下锤。',
    icon: bridgeArt,
    views: [
      {
        id: 'span',
        name: '桥面',
        background: bridgeBg,
        hotspots: [
          { id: 'bridge-cable-hotspot', partId: 'bridge-cable', x: 0.22, y: 0.24, width: 0.22, height: 0.34 },
          { id: 'bridge-midpoint-hotspot', partId: 'bridge-midpoint', x: 0.44, y: 0.5, width: 0.28, height: 0.16 },
          { id: 'bridge-pier-hotspot', partId: 'bridge-pier', x: 0.72, y: 0.42, width: 0.16, height: 0.32 },
        ],
      },
    ],
    parts: [
      {
        id: 'bridge-cable',
        name: '主缆束',
        viewId: 'span',
        material: 'metal',
        hp: 420,
        stages: [
          { id: 'tight', threshold: 1, art: bridgeArt, label: '主缆绷紧' },
          { id: 'fray', threshold: 0.45, art: bridgeArt, label: '钢索散开' },
          { id: 'cut', threshold: 0, art: bridgeArt, label: '主缆断开' },
        ],
        machineSlots: [{ id: 'bridge-cable-pipeline', accepts: ['pipeline', 'remote'], x: 0.3, y: 0.38 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'critical', threshold: 0.45, hint: '桥面开始把声音传到远处。' }],
      },
      {
        id: 'bridge-midpoint',
        name: '桥的中间',
        viewId: 'span',
        material: 'stone',
        hp: 460,
        stages: [
          { id: 'there', threshold: 1, art: bridgeArt, label: '中间还在' },
          { id: 'crack', threshold: 0.45, art: bridgeArt, label: '中间开裂' },
          { id: 'gone', threshold: 0, art: bridgeArt, label: '中间不见了' },
        ],
        machineSlots: [{ id: 'bridge-mid-mecha', accepts: ['mecha', 'pipeline'], x: 0.55, y: 0.56 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'critical', threshold: 0.35, hint: '老哥忽然意识到“中间”也算战利品。' }],
        requiredTags: ['pipeline', 'mecha', 'gundam'],
      },
      {
        id: 'bridge-pier',
        name: '桥墩外壳',
        viewId: 'span',
        material: 'stone',
        hp: 380,
        stages: [
          { id: 'solid', threshold: 1, art: bridgeArt, label: '桥墩结实' },
          { id: 'split', threshold: 0.45, art: bridgeArt, label: '桥墩裂开' },
          { id: 'open', threshold: 0, art: bridgeArt, label: '桥墩露芯' },
        ],
        machineSlots: [{ id: 'bridge-pier-pipeline', accepts: ['pipeline', 'hydraulic'], x: 0.76, y: 0.5 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'suspicious', threshold: 0.4, hint: '桥墩里嵌着一块陨石同款材料。' }],
      },
    ],
    risks: [
      { riskId: 'world-structure-collapse', partIds: ['bridge-cable', 'bridge-midpoint'] },
      { riskId: 'anomaly-meteor-core', partIds: ['bridge-pier'] },
    ],
    rewards: {
      cash: 7200,
      scrap: 520,
      items: ['u_midpoint', 'e_titanium', 'r_alloyblock'],
      rumors: ['rumor-mecha-frame', 'rumor-gundam-factory'],
      accidentArchives: ['archive-bridge-collapse'],
      reputation: 7,
    },
    entryCost: { money: 3400, reputation: 5 },
    unlocks: [
      { kind: 'source', id: 'mecha-fist' },
      { kind: 'source', id: 'mecha-shoulder-ram' },
      { kind: 'target', id: 'expedition-gundam-factory' },
    ],
  },
  {
    id: 'expedition-nuclear',
    name: '旧核电站反应堆',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '这玩意儿砸得慢，砸错了下一轮也会闻到。',
    icon: nuclearArt,
    views: [
      {
        id: 'reactor',
        name: '反应堆',
        background: nuclearBg,
        hotspots: [
          { id: 'reactor-shield-hotspot', partId: 'reactor-shield', x: 0.28, y: 0.26, width: 0.34, height: 0.3 },
          { id: 'fuel-rod-hotspot', partId: 'fuel-rod', x: 0.56, y: 0.44, width: 0.2, height: 0.24 },
          { id: 'cooling-pipe-hotspot', partId: 'cooling-pipe', x: 0.2, y: 0.58, width: 0.36, height: 0.12 },
        ],
      },
    ],
    parts: [
      {
        id: 'reactor-shield',
        name: '反应堆屏蔽层',
        viewId: 'reactor',
        material: 'stone',
        hp: 520,
        stages: [
          { id: 'sealed', threshold: 1, art: nuclearArt, label: '屏蔽层完整' },
          { id: 'glow', threshold: 0.45, art: nuclearArt, label: '缝隙发热' },
          { id: 'open', threshold: 0, art: nuclearArt, label: '屏蔽层打开' },
        ],
        machineSlots: [{ id: 'reactor-pipeline', accepts: ['pipeline', 'remote'], x: 0.44, y: 0.42 }],
        riskTriggers: [{ riskId: 'pollution-reactor-leak', level: 'dangerous', threshold: 0.5, hint: '屏蔽层裂缝里的光不是火。' }],
      },
      {
        id: 'fuel-rod',
        name: '燃料棒',
        viewId: 'reactor',
        material: 'volatile',
        hp: 180,
        stages: [
          { id: 'hot', threshold: 1, art: nuclearArt, label: '还温热' },
          { id: 'unstable', threshold: 0.45, art: nuclearArt, label: '读数乱跳' },
          { id: 'pulled', threshold: 0, art: nuclearArt, label: '燃料棒取出' },
        ],
        machineSlots: [{ id: 'fuel-rod-remote', accepts: ['remote'], x: 0.63, y: 0.54 }],
        riskTriggers: [{ riskId: 'pollution-reactor-leak', level: 'critical', threshold: 0.45, hint: '老哥觉得这下不该近身。' }],
      },
      {
        id: 'cooling-pipe',
        name: '冷却管线',
        viewId: 'reactor',
        material: 'metal',
        hp: 260,
        stages: [
          { id: 'blocked', threshold: 1, art: nuclearArt, label: '冷却管堵住' },
          { id: 'steam', threshold: 0.45, art: nuclearArt, label: '蒸汽喷出' },
          { id: 'clear', threshold: 0, art: nuclearArt, label: '管线清开' },
        ],
        machineSlots: [{ id: 'cooling-pipeline', accepts: ['pipeline', 'hydraulic'], x: 0.36, y: 0.62 }],
        riskTriggers: [{ riskId: 'corrosion-black-vault', level: 'suspicious', threshold: 0.35, hint: '管壁被某种黑色物质腐蚀过。' }],
      },
    ],
    risks: [
      { riskId: 'pollution-reactor-leak', partIds: ['reactor-shield', 'fuel-rod'] },
      { riskId: 'corrosion-black-vault', partIds: ['cooling-pipe'] },
    ],
    rewards: {
      cash: 7800,
      scrap: 420,
      items: ['u_fuelrod', 'e_uranium', 'titanium'],
      rumors: ['rumor-space-route', 'rumor-ufo-hull'],
      accidentArchives: ['archive-reactor-leak'],
      reputation: 7,
    },
    entryCost: { money: 4200, reputation: 6 },
    unlocks: [
      { kind: 'target', id: 'expedition-station' },
      { kind: 'target', id: 'expedition-collider' },
    ],
  },
  {
    id: 'expedition-station',
    name: '坠落空间站舱段',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '它还没完全落地，老哥已经在问怎么上去砸。',
    icon: stationArt,
    views: [
      {
        id: 'module',
        name: '舱段',
        background: stationBg,
        hotspots: [
          { id: 'station-hull-hotspot', partId: 'station-hull', x: 0.24, y: 0.34, width: 0.34, height: 0.24 },
          { id: 'station-airlock-hotspot', partId: 'station-airlock', x: 0.56, y: 0.4, width: 0.2, height: 0.22 },
          { id: 'station-coffee-hotspot', partId: 'zero-g-coffee', x: 0.42, y: 0.58, width: 0.18, height: 0.12 },
        ],
      },
    ],
    parts: [
      {
        id: 'station-hull',
        name: '舱段外壳',
        viewId: 'module',
        material: 'metal',
        hp: 520,
        stages: [
          { id: 'sealed', threshold: 1, art: stationArt, label: '外壳完整' },
          { id: 'punctured', threshold: 0.45, art: stationArt, label: '外壳穿孔' },
          { id: 'open', threshold: 0, art: stationArt, label: '舱段打开' },
        ],
        machineSlots: [{ id: 'station-hull-gundam', accepts: ['gundam', 'pipeline'], x: 0.4, y: 0.44 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'dangerous', threshold: 0.45, hint: '舱段开始离开地面几厘米。' }],
        requiredTags: ['pipeline', 'mecha', 'gundam'],
      },
      {
        id: 'station-airlock',
        name: '气闸门',
        viewId: 'module',
        material: 'volatile',
        hp: 220,
        stages: [
          { id: 'locked', threshold: 1, art: stationArt, label: '气闸锁死' },
          { id: 'hissing', threshold: 0.45, art: stationArt, label: '压力外泄' },
          { id: 'open', threshold: 0, art: stationArt, label: '气闸开了' },
        ],
        machineSlots: [{ id: 'airlock-remote', accepts: ['remote'], x: 0.64, y: 0.5 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'dangerous', threshold: 0.4, hint: '气闸后面没有空气，也没有正常方向。' }],
      },
      {
        id: 'zero-g-coffee',
        name: '失重咖啡箱',
        viewId: 'module',
        material: 'anomaly',
        hp: 160,
        stages: [
          { id: 'floating', threshold: 1, art: stationArt, label: '咖啡浮着' },
          { id: 'spinning', threshold: 0.45, art: stationArt, label: '杯子乱转' },
          { id: 'caught', threshold: 0, art: stationArt, label: '咖啡入账' },
        ],
        machineSlots: [{ id: 'coffee-remote', accepts: ['remote'], x: 0.48, y: 0.62 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'suspicious', threshold: 0.35, hint: '咖啡没有洒，物理学先洒了。' }],
      },
    ],
    risks: [
      { riskId: 'world-structure-collapse', partIds: ['station-hull'] },
      { riskId: 'anomaly-meteor-core', partIds: ['station-airlock', 'zero-g-coffee'] },
    ],
    rewards: {
      cash: 9000,
      scrap: 620,
      items: ['u_zerogcoffee', 'milchip', 'alienalloy'],
      rumors: ['rumor-ufo-hull', 'rumor-ultra-signal'],
      accidentArchives: ['archive-meteor-gravity'],
      reputation: 8,
    },
    entryCost: { money: 5600, reputation: 7 },
    unlocks: [{ kind: 'target', id: 'ufo-hull' }],
  },
  {
    id: 'expedition-collider',
    name: '粒子对撞机环段',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '管线在地下绕了一圈，老哥说这不就是更长的胶带吗。',
    icon: colliderArt,
    views: [
      {
        id: 'ring',
        name: '环段',
        background: colliderBg,
        hotspots: [
          { id: 'collider-ring-hotspot', partId: 'collider-ring', x: 0.22, y: 0.42, width: 0.42, height: 0.18 },
          { id: 'singularity-hotspot', partId: 'singularity-bottle', x: 0.58, y: 0.36, width: 0.18, height: 0.2 },
          { id: 'control-room-hotspot', partId: 'collider-control', x: 0.72, y: 0.48, width: 0.18, height: 0.16 },
        ],
      },
    ],
    parts: [
      {
        id: 'collider-ring',
        name: '对撞环',
        viewId: 'ring',
        material: 'metal',
        hp: 560,
        stages: [
          { id: 'charged', threshold: 1, art: colliderArt, label: '对撞环带电' },
          { id: 'warped', threshold: 0.45, art: colliderArt, label: '环段扭曲' },
          { id: 'split', threshold: 0, art: colliderArt, label: '对撞环断开' },
        ],
        machineSlots: [{ id: 'collider-ring-gundam', accepts: ['gundam', 'pipeline'], x: 0.42, y: 0.5 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'critical', threshold: 0.45, hint: '对撞环里面开始出现不是这里的光。' }],
        requiredTags: ['pipeline', 'gundam'],
      },
      {
        id: 'singularity-bottle',
        name: '奇点瓶',
        viewId: 'ring',
        material: 'anomaly',
        hp: 190,
        stages: [
          { id: 'sealed', threshold: 1, art: colliderArt, label: '奇点封住' },
          { id: 'thin', threshold: 0.45, art: colliderArt, label: '瓶壁变薄' },
          { id: 'caught', threshold: 0, art: colliderArt, label: '奇点收下' },
        ],
        machineSlots: [{ id: 'singularity-remote', accepts: ['remote', 'gundam'], x: 0.64, y: 0.46 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'critical', threshold: 0.35, hint: '奇点瓶把锤声吸没了。' }],
      },
      {
        id: 'collider-control',
        name: '控制室',
        viewId: 'ring',
        material: 'volatile',
        hp: 180,
        stages: [
          { id: 'locked', threshold: 1, art: colliderArt, label: '控制室锁死' },
          { id: 'sparking', threshold: 0.45, art: colliderArt, label: '屏幕倒放' },
          { id: 'open', threshold: 0, art: colliderArt, label: '控制室打开' },
        ],
        machineSlots: [{ id: 'collider-control-remote', accepts: ['remote'], x: 0.78, y: 0.56 }],
        riskTriggers: [{ riskId: 'anomaly-monolith-echo', level: 'suspicious', threshold: 0.3, hint: '屏幕里出现了黑方碑的倒影。' }],
      },
    ],
    risks: [
      { riskId: 'anomaly-meteor-core', partIds: ['collider-ring', 'singularity-bottle'] },
      { riskId: 'anomaly-monolith-echo', partIds: ['collider-control'] },
    ],
    rewards: {
      cash: 9800,
      scrap: 680,
      items: ['u_singularity', 'antimatter', 'e_rare'],
      rumors: ['rumor-ufo-hull', 'rumor-monolith-contract'],
      accidentArchives: ['archive-monolith-echo'],
      reputation: 8,
    },
    entryCost: { money: 6200, reputation: 7 },
    unlocks: [
      { kind: 'target', id: 'ufo-hull' },
      { kind: 'target', id: 'living-mecha-beast' },
    ],
  },
  {
    id: 'expedition-gundam-factory',
    name: '巨型机械工厂',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '厂房里有个比厂房更像厂房的东西。',
    icon: gundamArt,
    views: [
      {
        id: 'bay',
        name: '装配湾',
        background: gundamFactoryBg,
        hotspots: [
          { id: 'mecha-arm-hotspot', partId: 'mecha-arm', x: 0.22, y: 0.32, width: 0.2, height: 0.34 },
          { id: 'gundam-cockpit-hotspot', partId: 'gundam-cockpit', x: 0.46, y: 0.28, width: 0.22, height: 0.24 },
          { id: 'justice-core-hotspot', partId: 'justice-core', x: 0.58, y: 0.5, width: 0.22, height: 0.2 },
        ],
      },
    ],
    parts: [
      {
        id: 'mecha-arm',
        name: '残机巨臂',
        viewId: 'bay',
        material: 'metal',
        hp: 520,
        stages: [
          { id: 'hanging', threshold: 1, art: mechaArt, label: '巨臂挂着' },
          { id: 'loose', threshold: 0.45, art: mechaArt, label: '关节松动' },
          { id: 'claimed', threshold: 0, art: mechaArt, label: '巨臂归老哥' },
        ],
        machineSlots: [{ id: 'mecha-arm-mecha', accepts: ['mecha', 'pipeline'], x: 0.32, y: 0.48 }],
        riskTriggers: [{ riskId: 'legal-city-response', level: 'dangerous', threshold: 0.45, hint: '工厂广播开始喊“停止破坏正义财产”。' }],
        requiredTags: ['mecha', 'pipeline'],
      },
      {
        id: 'gundam-cockpit',
        name: '高达驾驶舱',
        viewId: 'bay',
        material: 'metal',
        hp: 420,
        stages: [
          { id: 'sealed', threshold: 1, art: gundamArt, label: '驾驶舱封住' },
          { id: 'open', threshold: 0.45, art: gundamArt, label: '舱门开缝' },
          { id: 'online', threshold: 0, art: gundamArt, label: '驾驶舱上线' },
        ],
        machineSlots: [{ id: 'gundam-cockpit-mecha', accepts: ['mecha', 'remote'], x: 0.56, y: 0.38 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'dangerous', threshold: 0.35, hint: '高达残机开始自己站起来。' }],
        requiredTags: ['mecha', 'pipeline'],
      },
      {
        id: 'justice-core',
        name: '正义流水线核心',
        viewId: 'bay',
        material: 'anomaly',
        hp: 260,
        stages: [
          { id: 'judging', threshold: 1, art: gundamArt, label: '核心在审判' },
          { id: 'angry', threshold: 0.45, art: gundamArt, label: '核心红了' },
          { id: 'owned', threshold: 0, art: gundamArt, label: '核心被砸服' },
        ],
        machineSlots: [{ id: 'justice-core-remote', accepts: ['remote', 'mecha'], x: 0.68, y: 0.58 }],
        riskTriggers: [{ riskId: 'anomaly-monolith-echo', level: 'dangerous', threshold: 0.35, hint: '核心说老哥不够正义，老哥说你不够结实。' }],
      },
    ],
    risks: [
      { riskId: 'legal-city-response', partIds: ['mecha-arm'] },
      { riskId: 'world-structure-collapse', partIds: ['gundam-cockpit'] },
      { riskId: 'anomaly-monolith-echo', partIds: ['justice-core'] },
    ],
    rewards: {
      cash: 12000,
      scrap: 900,
      items: ['u_justicecore', 'mechcore', 'persona'],
      rumors: ['rumor-gundam-factory', 'rumor-ufo-hull'],
      accidentArchives: ['archive-monolith-echo'],
      reputation: 10,
    },
    entryCost: { money: 7600, reputation: 8 },
    unlocks: [
      { kind: 'source', id: 'gundam-pile' },
      { kind: 'target', id: 'ufo-hull' },
      { kind: 'target', id: 'living-mecha-beast' },
    ],
  },
  {
    id: 'ufo-hull',
    name: '外星飞船外壳',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '飞船不肯降落，老哥开着高达让它讲道理。',
    icon: ufoArt,
    views: [
      {
        id: 'hull',
        name: '船壳',
        background: stationBg,
        hotspots: [
          { id: 'ufo-hull-hotspot', partId: 'ufo-outer-hull', x: 0.24, y: 0.34, width: 0.36, height: 0.24 },
          { id: 'ufo-drive-hotspot', partId: 'ufo-drive', x: 0.56, y: 0.42, width: 0.24, height: 0.2 },
          { id: 'ufo-core-hotspot', partId: 'ufo-core', x: 0.42, y: 0.54, width: 0.22, height: 0.18 },
        ],
      },
    ],
    parts: [
      {
        id: 'ufo-outer-hull',
        name: '飞船外壳',
        viewId: 'hull',
        material: 'anomaly',
        hp: 660,
        stages: [
          { id: 'smooth', threshold: 1, art: ufoArt, label: '没有受力点' },
          { id: 'dent', threshold: 0.45, art: ufoArt, label: '船壳凹下去' },
          { id: 'split', threshold: 0, art: ufoArt, label: '船壳裂开' },
        ],
        machineSlots: [{ id: 'ufo-hull-gundam', accepts: ['gundam'], x: 0.42, y: 0.44 }],
        riskTriggers: [{ riskId: 'anomaly-monolith-echo', level: 'dangerous', threshold: 0.45, hint: '船壳反射出一个黑色长方体。' }],
        requiredTags: ['gundam'],
      },
      {
        id: 'ufo-drive',
        name: '反重力驱动',
        viewId: 'hull',
        material: 'anomaly',
        hp: 360,
        stages: [
          { id: 'spinning', threshold: 1, art: ufoArt, label: '驱动在转' },
          { id: 'unstable', threshold: 0.45, art: ufoArt, label: '重力乱飘' },
          { id: 'removed', threshold: 0, art: ufoArt, label: '驱动拆下' },
        ],
        machineSlots: [{ id: 'ufo-drive-remote', accepts: ['remote', 'gundam'], x: 0.68, y: 0.5 }],
        riskTriggers: [{ riskId: 'anomaly-meteor-core', level: 'critical', threshold: 0.4, hint: '驱动让老哥的锤子先到了再挥。' }],
        requiredTags: ['remote', 'gundam'],
      },
      {
        id: 'ufo-core',
        name: '飞船活体核心',
        viewId: 'hull',
        material: 'organic',
        hp: 300,
        stages: [
          { id: 'alive', threshold: 1, art: ufoArt, label: '核心在看' },
          { id: 'angry', threshold: 0.45, art: ufoArt, label: '核心开始反击' },
          { id: 'claimed', threshold: 0, art: ufoArt, label: '核心到手' },
        ],
        machineSlots: [{ id: 'ufo-core-gundam', accepts: ['gundam', 'ultra'], x: 0.52, y: 0.6 }],
        riskTriggers: [{ riskId: 'bio-egg-hatch', level: 'critical', threshold: 0.45, hint: '核心和黑市蛋像是亲戚。' }],
        requiredTags: ['gundam', 'ultra'],
      },
    ],
    risks: [
      { riskId: 'anomaly-monolith-echo', partIds: ['ufo-outer-hull'] },
      { riskId: 'anomaly-meteor-core', partIds: ['ufo-drive'] },
      { riskId: 'bio-egg-hatch', partIds: ['ufo-core'] },
    ],
    rewards: {
      cash: 16000,
      scrap: 1200,
      items: ['ufo', 'alienalloy', 'antimatter'],
      rumors: ['rumor-ultra-signal', 'rumor-monolith-contract'],
      accidentArchives: ['archive-monolith-echo'],
      reputation: 12,
    },
    entryCost: { money: 9800, reputation: 10 },
    unlocks: [
      { kind: 'source', id: 'ultra-beam' },
      { kind: 'source', id: 'ultra-stomp' },
      { kind: 'source', id: 'ultra-flying-kick' },
      { kind: 'target', id: 'living-mecha-beast' },
    ],
  },
  {
    id: 'living-mecha-beast',
    name: '怪兽级活体机械',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '它不是机器，也不是怪兽，它是欠砸的两者交界处。',
    icon: mechaArt,
    views: [
      {
        id: 'beast',
        name: '躯体',
        background: reactorBg,
        hotspots: [
          { id: 'beast-armor-hotspot', partId: 'beast-armor', x: 0.24, y: 0.34, width: 0.32, height: 0.26 },
          { id: 'beast-heart-hotspot', partId: 'beast-heart', x: 0.5, y: 0.46, width: 0.22, height: 0.2 },
          { id: 'beast-claw-hotspot', partId: 'beast-claw', x: 0.64, y: 0.3, width: 0.2, height: 0.28 },
        ],
      },
    ],
    parts: [
      {
        id: 'beast-armor',
        name: '活体装甲',
        viewId: 'beast',
        material: 'organic',
        hp: 620,
        stages: [
          { id: 'covered', threshold: 1, art: mechaArt, label: '装甲在长' },
          { id: 'hurt', threshold: 0.45, art: mechaArt, label: '装甲流金属' },
          { id: 'open', threshold: 0, art: mechaArt, label: '装甲破开' },
        ],
        machineSlots: [{ id: 'beast-armor-gundam', accepts: ['gundam', 'ultra'], x: 0.4, y: 0.46 }],
        riskTriggers: [{ riskId: 'bio-egg-hatch', level: 'critical', threshold: 0.45, hint: '活体装甲开始学老哥的砸法。' }],
        requiredTags: ['gundam', 'ultra'],
      },
      {
        id: 'beast-heart',
        name: '机械心脏',
        viewId: 'beast',
        material: 'anomaly',
        hp: 360,
        stages: [
          { id: 'beating', threshold: 1, art: mechaArt, label: '心脏轰鸣' },
          { id: 'exposed', threshold: 0.45, art: mechaArt, label: '心脏暴露' },
          { id: 'stopped', threshold: 0, art: mechaArt, label: '心脏停下' },
        ],
        machineSlots: [{ id: 'beast-heart-ultra', accepts: ['ultra', 'gundam'], x: 0.58, y: 0.54 }],
        riskTriggers: [{ riskId: 'anomaly-monolith-echo', level: 'critical', threshold: 0.4, hint: '心跳里夹着黑方碑的回声。' }],
        requiredTags: ['gundam', 'ultra'],
      },
      {
        id: 'beast-claw',
        name: '反击巨爪',
        viewId: 'beast',
        material: 'metal',
        hp: 420,
        stages: [
          { id: 'ready', threshold: 1, art: mechaArt, label: '巨爪抬起' },
          { id: 'broken', threshold: 0.45, art: mechaArt, label: '指节断裂' },
          { id: 'taken', threshold: 0, art: mechaArt, label: '巨爪拆下' },
        ],
        machineSlots: [{ id: 'beast-claw-gundam', accepts: ['gundam', 'mecha'], x: 0.74, y: 0.44 }],
        riskTriggers: [{ riskId: 'world-structure-collapse', level: 'dangerous', threshold: 0.4, hint: '它会反砸，工具也会碎。' }],
        requiredTags: ['gundam', 'mecha'],
      },
    ],
    risks: [
      { riskId: 'bio-egg-hatch', partIds: ['beast-armor'] },
      { riskId: 'anomaly-monolith-echo', partIds: ['beast-heart'] },
      { riskId: 'world-structure-collapse', partIds: ['beast-claw'] },
    ],
    rewards: {
      cash: 19000,
      scrap: 1500,
      items: ['livingmetal', 'mechcore', 'persona'],
      rumors: ['rumor-monolith-contract'],
      accidentArchives: ['archive-monolith-echo'],
      reputation: 14,
    },
    entryCost: { money: 12000, reputation: 12 },
    unlocks: [{ kind: 'target', id: 'black-monolith' }],
  },
  {
    id: 'black-monolith',
    name: '不反光的黑方碑',
    scale: 'site',
    presentation: 'scene',
    phase: 'p2',
    intro: '它一直在每轮事故后看着老哥，这次轮到老哥看它裂开。',
    icon: monolithArt,
    sellerId: 'monolith',
    views: [
      {
        id: 'face',
        name: '正面',
        background: reactorBg,
        hotspots: [
          { id: 'monolith-face-hotspot', partId: 'monolith-face', x: 0.36, y: 0.18, width: 0.28, height: 0.46 },
          { id: 'monolith-shadow-hotspot', partId: 'monolith-shadow', x: 0.28, y: 0.56, width: 0.42, height: 0.2 },
        ],
      },
      {
        id: 'rift',
        name: '裂隙',
        background: reactorBg,
        hotspots: [
          { id: 'monolith-rift-hotspot', partId: 'monolith-rift', x: 0.42, y: 0.26, width: 0.2, height: 0.34 },
        ],
      },
    ],
    parts: [
      {
        id: 'monolith-face',
        name: '无反光表面',
        viewId: 'face',
        material: 'anomaly',
        hp: 820,
        stages: [
          { id: 'perfect', threshold: 1, art: monolithArt, label: '没有任何划痕' },
          { id: 'singing', threshold: 0.45, art: monolithArt, label: '表面开始唱倒放歌' },
          { id: 'scarred', threshold: 0, art: monolithArt, label: '表面留下第一道痕' },
        ],
        machineSlots: [{ id: 'monolith-face-gundam', accepts: ['gundam', 'ultra'], x: 0.5, y: 0.42 }],
        riskTriggers: [{ riskId: 'anomaly-monolith-echo', level: 'critical', threshold: 0.55, hint: '每一锤都像砸在上一轮的自己身上。' }],
        requiredTags: ['gundam', 'ultra'],
        unlocksViews: ['rift'],
        unlocksParts: ['monolith-rift'],
      },
      {
        id: 'monolith-shadow',
        name: '没有来源的影子',
        viewId: 'face',
        material: 'anomaly',
        hp: 460,
        stages: [
          { id: 'flat', threshold: 1, art: monolithArt, label: '影子很平' },
          { id: 'thick', threshold: 0.45, art: monolithArt, label: '影子变厚' },
          { id: 'cut', threshold: 0, art: monolithArt, label: '影子被砸断' },
        ],
        machineSlots: [{ id: 'monolith-shadow-ultra', accepts: ['ultra', 'remote'], x: 0.48, y: 0.64 }],
        riskTriggers: [{ riskId: 'mutation-giant-overload', level: 'dangerous', threshold: 0.4, hint: '巨大化倒计时忽然变短。' }],
        requiredTags: ['ultra'],
      },
      {
        id: 'monolith-rift',
        name: '终局裂隙',
        viewId: 'rift',
        material: 'anomaly',
        hp: 620,
        stages: [
          { id: 'closed', threshold: 1, art: monolithArt, label: '裂隙闭合' },
          { id: 'open', threshold: 0.45, art: monolithArt, label: '裂隙张开' },
          { id: 'broken', threshold: 0, art: monolithArt, label: '黑方碑破裂' },
        ],
        machineSlots: [{ id: 'monolith-rift-ultra', accepts: ['ultra'], x: 0.52, y: 0.44 }],
        riskTriggers: [{ riskId: 'anomaly-monolith-echo', level: 'critical', threshold: 0.4, hint: '它开始把所有传闻倒着吐出来。' }],
        requiredTags: ['ultra'],
      },
    ],
    risks: [
      { riskId: 'anomaly-monolith-echo', partIds: ['monolith-face', 'monolith-rift'] },
      { riskId: 'mutation-giant-overload', partIds: ['monolith-shadow'] },
    ],
    rewards: {
      cash: 30000,
      scrap: 2500,
      items: ['antimatter', 'persona', 'livingmetal', 'u_singularity'],
      rumors: [],
      accidentArchives: ['archive-monolith-echo', 'archive-ultra-overload'],
      reputation: 20,
    },
    entryCost: { money: 18000, reputation: 16 },
    unlocks: [{ kind: 'panel', id: 'postgame' }],
  },
];

export const P2_TARGET_MAP = Object.fromEntries(P2_TARGETS.map((target) => [target.id, target]));
